<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        DB::unprepared("
            CREATE TABLE veterinarios (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                nombreCompleto VARCHAR2(255) NOT NULL,
                fechaInicio DATE NOT NULL,
                telefono VARCHAR2(50) NOT NULL,
                especialidad VARCHAR2(255) NOT NULL,
                idUsuario NUMBER NOT NULL,
                CONSTRAINT fk_veterinarios_usuarios FOREIGN KEY (idUsuario) REFERENCES usuarios(id)
            )
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarVeterinarios(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM veterinarios;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarVeterinarioPorId(p_id IN NUMBER, cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM veterinarios WHERE id = p_id;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarVeterinario(
                p_id IN NUMBER,
                p_nombreCompleto IN VARCHAR2,
                p_fechaInicio IN DATE,
                p_telefono IN VARCHAR2,
                p_especialidad IN VARCHAR2,
                p_idUsuario IN NUMBER
            ) IS
            BEGIN
                UPDATE veterinarios
                SET nombreCompleto = p_nombreCompleto,
                    fechaInicio = p_fechaInicio,
                    telefono = p_telefono,
                    especialidad = p_especialidad,
                    idUsuario = p_idUsuario
                WHERE id = p_id;
                COMMIT;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarVeterinarioPorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM veterinarios WHERE id = p_id;
                COMMIT;
            END;
        ");
    }
    
    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarVeterinarios");
        DB::unprepared("DROP PROCEDURE ConsultarVeterinarioPorId");
        DB::unprepared("DROP PROCEDURE ActualizarVeterinario");
        DB::unprepared("DROP PROCEDURE EliminarVeterinarioPorId");
        
        DB::unprepared("DROP TABLE veterinarios");
    }
};