<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Migración CreateVeterinariosTable
 *
 * Esta migración crea la tabla 'veterinarios' con las siguientes columnas:
 * - id: NUMBER generado como identidad (PRIMARY KEY)
 * - idUsuario: NUMBER NOT NULL (FOREIGN KEY a usuarios.id)
 *
 * Además define los procedimientos almacenados:
 * - ConsultarVeterinarios: devuelve todos los veterinarios con datos de usuario
 * - ConsultarVeterinarioPorId: devuelve un veterinario por ID
 * - ActualizarVeterinario: actualiza el idUsuario de un veterinario
 * - EliminarVeterinarioPorId: elimina un veterinario por ID
 * - EliminarVeterinarioPorUsuarioId: elimina un veterinario por usuario ID
 * - InsertarVeterinario: inserta un veterinario y retorna su ID
 */
return new class extends Migration {
    public function up(): void
    {
        // Crea la tabla veterinarios
        DB::unprepared("
            CREATE TABLE veterinarios (
                id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                idUsuario NUMBER                NOT NULL,
                CONSTRAINT fk_veterinarios_usuarios 
                  FOREIGN KEY (idUsuario) REFERENCES usuarios(id)
            )
        ");

        // SP: consultar todos los veterinarios con datos de usuario
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarVeterinarios(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR
                SELECT
                  v.id,
                  u.id             AS idUsuario,
                  u.email          AS correo,
                  u.rol,
                  u.nombre_completo,
                  u.telefono,
                  u.en_recuperacion
                FROM veterinarios v
                JOIN usuarios u ON v.idUsuario = u.id;
            END;
        ");

        // SP: consultar un veterinario por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarVeterinarioPorId(
                p_id IN NUMBER,
                cur  OUT SYS_REFCURSOR
            ) IS
            BEGIN
                OPEN cur FOR
                SELECT
                  v.id,
                  u.id             AS idUsuario,
                  u.email          AS correo,
                  u.rol,
                  u.nombre_completo,
                  u.telefono,
                  u.en_recuperacion
                FROM veterinarios v
                JOIN usuarios u ON v.idUsuario = u.id
               WHERE v.id = p_id;
            END;
        ");

        // SP: actualizar un veterinario (solo idUsuario)
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarVeterinario(
                p_id        IN NUMBER,
                p_idUsuario IN NUMBER
            ) IS
            BEGIN
                UPDATE veterinarios
                   SET idUsuario = p_idUsuario
                 WHERE id = p_id;
                COMMIT;
            END;
        ");

        // SP: eliminar un veterinario por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarVeterinarioPorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM veterinarios WHERE id = p_id;
                COMMIT;
            END;
        ");

        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarVeterinarioPorUsuarioId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM veterinarios WHERE idUsuario = p_id;
                COMMIT;
            END;
        ");

        // SP: insertar un veterinario (solo idUsuario) y retornar su id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE InsertarVeterinario(
                p_idUsuario IN NUMBER,
                p_id        OUT NUMBER
            ) IS
            BEGIN
                INSERT INTO veterinarios (idUsuario)
                VALUES (p_idUsuario)
                RETURNING id INTO p_id;
                COMMIT;
            END;
        ");
    }

    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarVeterinarios");
        DB::unprepared("DROP PROCEDURE ConsultarVeterinarioPorId");
        DB::unprepared("DROP PROCEDURE ActualizarVeterinario");
        DB::unprepared("DROP PROCEDURE EliminarVeterinarioPorId");
        DB::unprepared("DROP PROCEDURE EliminarVeterinarioPorUsuarioId");
        DB::unprepared("DROP PROCEDURE InsertarVeterinario");
        DB::unprepared("DROP TABLE veterinarios");
    }
};