<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        // Tabla sucursales
        DB::unprepared("
            CREATE TABLE sucursales (
                id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                nombre     VARCHAR2(255) NOT NULL,
                direccion  VARCHAR2(255) NOT NULL
            )
        ");

        // SP: Consultar todas las sucursales
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarSucursales(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR
                  SELECT id, nombre, direccion
                    FROM sucursales;
            END;
        ");

        // SP: Consultar sucursal por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarSucursalPorId(
                p_id IN NUMBER,
                cur  OUT SYS_REFCURSOR
            ) IS
            BEGIN
                OPEN cur FOR
                  SELECT id, nombre, direccion
                    FROM sucursales
                   WHERE id = p_id;
            END;
        ");

        // SP: Insertar sucursal
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE InsertarSucursal(
                p_nombre    IN VARCHAR2,
                p_direccion IN VARCHAR2,
                p_id        OUT NUMBER
            ) IS
            BEGIN
                INSERT INTO sucursales(nombre, direccion)
                VALUES (p_nombre, p_direccion)
                RETURNING id INTO p_id;
                COMMIT;
            END;
        ");

        // SP: Actualizar sucursal
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarSucursal(
                p_id        IN NUMBER,
                p_nombre    IN VARCHAR2,
                p_direccion IN VARCHAR2
            ) IS
            BEGIN
                UPDATE sucursales
                   SET nombre    = p_nombre,
                       direccion = p_direccion
                 WHERE id = p_id;
                COMMIT;
            END;
        ");

        // SP: Eliminar sucursal por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarSucursalPorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM sucursales WHERE id = p_id;
                COMMIT;
            END;
        ");
    }

    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarSucursales");
        DB::unprepared("DROP PROCEDURE ConsultarSucursalPorId");
        DB::unprepared("DROP PROCEDURE InsertarSucursal");
        DB::unprepared("DROP PROCEDURE ActualizarSucursal");
        DB::unprepared("DROP PROCEDURE EliminarSucursalPorId");
        DB::unprepared("DROP TABLE sucursales");
    }
};