<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        DB::unprepared("
            CREATE TABLE mascotas (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                nombreCompleto VARCHAR2(255) NOT NULL,
                edad NUMBER NOT NULL,
                peso NUMBER(5,2) NOT NULL,
                raza VARCHAR2(255) NOT NULL,
                especie VARCHAR2(255) NOT NULL,
                idCliente NUMBER NOT NULL,
                CONSTRAINT fk_mascotas_clientes FOREIGN KEY (idCliente) REFERENCES clientes(id)
            )
        ");

        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarMascotas(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM mascotas;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarMascotaPorId(p_id IN NUMBER, cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM mascotas WHERE id = p_id;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarMascota(
                p_id IN NUMBER,
                p_nombreCompleto IN VARCHAR2,
                p_edad IN NUMBER,
                p_peso IN NUMBER,
                p_raza IN VARCHAR2,
                p_especie IN VARCHAR2,
                p_idCliente IN NUMBER
            ) IS
            BEGIN
                UPDATE mascotas
                SET nombreCompleto = p_nombreCompleto,
                    edad = p_edad,
                    peso = p_peso,
                    raza = p_raza,
                    especie = p_especie,
                    idCliente = p_idCliente
                WHERE id = p_id;
                COMMIT;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarMascotaPorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM mascotas WHERE id = p_id;
                COMMIT;
            END;
        ");
    }
    
    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarMascotas");
        DB::unprepared("DROP PROCEDURE ConsultarMascotaPorId");
        DB::unprepared("DROP PROCEDURE ActualizarMascota");
        DB::unprepared("DROP PROCEDURE EliminarMascotaPorId");
        DB::unprepared("DROP TABLE mascotas CASCADE CONSTRAINTS PURGE");
    }
};