<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Migración CreateClientesTable
 *
 * Esta migración crea la tabla 'clientes' con las siguientes columnas:
 * - id: NUMBER generado como identidad (PRIMARY KEY)
 * - direccion: VARCHAR2(255) NOT NULL
 * - idUsuario: NUMBER NOT NULL (FOREIGN KEY a usuarios.id)
 *
 * Además define los procedimientos almacenados:
 * - ConsultarClientes: devuelve todos los clientes con datos de usuario
 * - ConsultarClientePorId: devuelve un cliente por ID con datos de usuario
 * - ConsultarClienteIdPorIdUsuario: obtiene el ID del cliente a partir del ID de usuario
 * - ActualizarCliente: actualiza los datos de un cliente
 * - EliminarClientePorId: elimina un cliente por ID
 * - InsertarCliente: inserta un nuevo cliente y retorna su ID
 */
return new class extends Migration {
    public function up(): void
    {
        // Crea la tabla clientes (solo datos específicos de cliente)
        DB::unprepared("
            CREATE TABLE clientes (
                id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                direccion   VARCHAR2(255) NOT NULL,
                idUsuario   NUMBER NOT NULL,
                CONSTRAINT fk_clientes_usuarios FOREIGN KEY (idUsuario) REFERENCES usuarios(id)
            )
        ");

        // SP: consultar todos los clientes con datos de usuario
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarClientes(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR
                SELECT 
                  c.id,
                  c.direccion,
                  u.id             AS idUsuario,
                  u.email         AS correo,
                  u.rol,
                  u.nombre_completo,
                  u.telefono
                FROM clientes c
                JOIN usuarios u ON c.idUsuario = u.id;
            END;
        ");

        // SP: consultar un cliente por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarClientePorId(
                p_id IN NUMBER,
                cur  OUT SYS_REFCURSOR
            ) IS
            BEGIN
                OPEN cur FOR
                SELECT 
                  c.id,
                  c.direccion,
                  u.id             AS idUsuario,
                  u.email         AS correo,
                  u.rol,
                  u.nombre_completo,
                  u.telefono
                FROM clientes c
                JOIN usuarios u ON c.idUsuario = u.id
               WHERE c.id = p_id;
            END;
        ");

        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarClienteIdPorIdUsuario(
                p_idUsuario IN NUMBER,
                p_id        OUT NUMBER
            ) IS
            BEGIN
                SELECT id
                INTO p_id
                FROM clientes
                WHERE idUsuario = p_idUsuario;
            END;
        ");

        // SP: actualizar un cliente
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarCliente(
                p_id        IN NUMBER,
                p_direccion IN VARCHAR2,
                p_idUsuario IN NUMBER
            ) IS
            BEGIN
                UPDATE clientes
                   SET direccion = p_direccion,
                       idUsuario = p_idUsuario
                 WHERE id = p_id;
                COMMIT;
            END;
        ");

        // SP: eliminar un cliente por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarClientePorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM clientes WHERE id = p_id;
                COMMIT;
            END;
        ");

        // SP: insertar un cliente y retornar su id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE InsertarCliente(
                p_direccion IN VARCHAR2,
                p_idUsuario IN NUMBER,
                p_id        OUT NUMBER
            ) IS
            BEGIN
                INSERT INTO clientes (direccion, idUsuario)
                VALUES (p_direccion, p_idUsuario)
                RETURNING id INTO p_id;
                COMMIT;
            END;
        ");
    }

    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarClientes");
        DB::unprepared("DROP PROCEDURE ConsultarClientePorId");
        DB::unprepared("DROP PROCEDURE ConsultarClienteIdPorIdUsuario");
        DB::unprepared("DROP PROCEDURE ActualizarCliente");
        DB::unprepared("DROP PROCEDURE EliminarClientePorId");
        DB::unprepared("DROP PROCEDURE InsertarCliente");

        DB::unprepared("DROP TABLE clientes");
    }
};