<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        DB::unprepared("
            CREATE TABLE inventario (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                nombreProducto VARCHAR2(255) NOT NULL,
                descripcion CLOB NOT NULL,
                precio NUMBER(10,2) NOT NULL,
                cantidadUnidades NUMBER NOT NULL,
                fechaCaducidad DATE NOT NULL
            )
        ");

        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarInventario(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM inventario;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarInventarioPorId(p_id IN NUMBER, cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM inventario WHERE id = p_id;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarInventario(
                p_id IN NUMBER,
                p_nombreProducto IN VARCHAR2,
                p_descripcion IN CLOB,
                p_precio IN NUMBER,
                p_cantidadUnidades IN NUMBER,
                p_fechaCaducidad IN DATE
            ) IS
            BEGIN
                UPDATE inventario
                SET nombreProducto = p_nombreProducto,
                    descripcion = p_descripcion,
                    precio = p_precio,
                    cantidadUnidades = p_cantidadUnidades,
                    fechaCaducidad = p_fechaCaducidad
                WHERE id = p_id;
                COMMIT;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarInventarioPorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM inventario WHERE id = p_id;
                COMMIT;
            END;
        ");
    }
    
    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarInventario");
        DB::unprepared("DROP PROCEDURE ConsultarInventarioPorId");
        DB::unprepared("DROP PROCEDURE ActualizarInventario");
        DB::unprepared("DROP PROCEDURE EliminarInventarioPorId");
        
        DB::unprepared("DROP TABLE inventario CASCADE CONSTRAINTS PURGE");
    }
};