<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        DB::unprepared("
            CREATE TABLE citas (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                idMascota NUMBER NOT NULL,
                fechaInicio DATE NOT NULL,
                idServicio NUMBER NOT NULL,
                descripcion CLOB NOT NULL,
                asistencia NUMBER(1) NOT NULL,
                CONSTRAINT fk_citas_mascotas FOREIGN KEY (idMascota) REFERENCES mascotas(id),
                CONSTRAINT fk_citas_servicios FOREIGN KEY (idServicio) REFERENCES servicios(id)
            )
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarCitas(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR
                SELECT 
                c.id,
                m.nombre_completo AS mascota,
                s.nombre          AS servicio,
                c.fechaInicio,
                c.descripcion,
                c.asistencia
                FROM citas c
                JOIN mascotas m ON c.idMascota  = m.id
                JOIN servicios s ON c.idServicio = s.id;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarCitaPorId(
                p_id IN NUMBER,
                cur  OUT SYS_REFCURSOR
            ) IS
            BEGIN
                OPEN cur FOR
                SELECT 
                c.id,
                m.nombre_completo AS mascota,
                s.nombre          AS servicio,
                c.fechaInicio,
                c.descripcion,
                c.asistencia
                FROM citas c
                JOIN mascotas m ON c.idMascota  = m.id
                JOIN servicios s ON c.idServicio = s.id
            WHERE c.id = p_id;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarCita(
                p_id IN NUMBER,
                p_idMascota IN NUMBER,
                p_fechaInicio IN DATE,
                p_idServicio IN NUMBER,
                p_descripcion IN CLOB,
                p_asistencia IN NUMBER
            ) IS
            BEGIN
                UPDATE citas
                SET idMascota = p_idMascota,
                    fechaInicio = p_fechaInicio,
                    idServicio = p_idServicio,
                    descripcion = p_descripcion,
                    asistencia = p_asistencia
                WHERE id = p_id;
                COMMIT;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarCitaPorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM citas WHERE id = p_id;
                COMMIT;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE InsertarCita(
                p_idMascota IN NUMBER,
                p_fechaInicio IN DATE,
                p_idServicio IN NUMBER,
                p_descripcion IN CLOB,
                p_asistencia IN NUMBER,
                p_id OUT NUMBER
            ) IS
            BEGIN
                INSERT INTO citas (idMascota, fechaInicio, idServicio, descripcion, asistencia)
                VALUES (p_idMascota, p_fechaInicio, p_idServicio, p_descripcion, p_asistencia)
                RETURNING id INTO p_id;
                COMMIT;
            END;
        ");

        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarCitasConDetalles(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR 
                    SELECT 
                        c.id,
                        c.fechaInicio,
                        c.descripcion,
                        c.asistencia,
                        m.nombre_completo as nombre_mascota,
                        m.edad as edad_mascota,
                        m.peso as peso_mascota,
                        m.raza as raza_mascota,
                        m.especie as especie_mascota,
                        s.nombre as nombre_servicio,
                        u.nombre_completo as nombre_cliente,
                        u.telefono as telefono_cliente,
                        cl.direccion as direccion_cliente
                    FROM citas c
                    JOIN mascotas m ON c.idMascota = m.id
                    JOIN servicios s ON c.idServicio = s.id
                    JOIN clientes cl ON m.idCliente = cl.id
                    JOIN usuarios u ON cl.idUsuario = u.id
                    ORDER BY c.fechaInicio DESC;
            END;
        ");

        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarCitaConDetallesPorId(
                p_id IN NUMBER,
                cur OUT SYS_REFCURSOR
            ) IS
            BEGIN
                OPEN cur FOR 
                    SELECT 
                        c.id,
                        c.fechaInicio,
                        c.descripcion,
                        c.asistencia,
                        m.nombre_completo as nombre_mascota,
                        m.edad as edad_mascota,
                        m.peso as peso_mascota,
                        m.raza as raza_mascota,
                        m.especie as especie_mascota,
                        s.nombre as nombre_servicio,
                        s.precio as precio_servicio,
                        u.nombre_completo as nombre_cliente,
                        u.telefono as telefono_cliente,
                        cl.direccion as direccion_cliente
                    FROM citas c
                    JOIN mascotas m ON c.idMascota = m.id
                    JOIN servicios s ON c.idServicio = s.id
                    JOIN clientes cl ON m.idCliente = cl.id
                    JOIN usuarios u ON cl.idUsuario = u.id
                    WHERE c.id = p_id;
            END;
        ");

        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarAsistenciaCita(
                p_id IN NUMBER,
                p_asistencia IN NUMBER
            ) IS
            BEGIN
                UPDATE citas
                SET asistencia = p_asistencia
                WHERE id = p_id;
                COMMIT;
            END;
        ");

        // Add the stored procedure for getting user appointments with details
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarCitasConDetallesPorUsuario(
                p_usuario_id IN NUMBER,
                cur OUT SYS_REFCURSOR
            ) IS
            BEGIN
                OPEN cur FOR 
                    SELECT 
                        c.id,
                        c.fechaInicio,
                        c.descripcion,
                        c.asistencia,
                        m.nombre_completo as nombre_mascota,
                        m.edad as edad_mascota,
                        m.peso as peso_mascota,
                        m.raza as raza_mascota,
                        m.especie as especie_mascota,
                        s.nombre as nombre_servicio,
                        s.precio as precio_servicio,
                        u.nombre_completo as nombre_cliente,
                        u.telefono as telefono_cliente,
                        cl.direccion as direccion_cliente
                    FROM citas c
                    JOIN mascotas m ON c.idMascota = m.id
                    JOIN servicios s ON c.idServicio = s.id
                    JOIN clientes cl ON m.idCliente = cl.id
                    JOIN usuarios u ON cl.idUsuario = u.id
                    WHERE u.id = p_usuario_id
                    ORDER BY c.fechaInicio DESC;
            END;
        ");
    }
    
    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarCitas");
        DB::unprepared("DROP PROCEDURE ConsultarCitaPorId");
        DB::unprepared("DROP PROCEDURE ActualizarCita");
        DB::unprepared("DROP PROCEDURE EliminarCitaPorId");
        DB::unprepared("DROP PROCEDURE InsertarCita");
        DB::unprepared("DROP PROCEDURE ConsultarCitasConDetalles");
        DB::unprepared("DROP PROCEDURE ConsultarCitaConDetallesPorId");
        DB::unprepared("DROP PROCEDURE ActualizarAsistenciaCita");
        
        DB::unprepared("DROP PROCEDURE ConsultarCitasConDetallesPorUsuario");
        
        DB::unprepared("DROP TABLE citas");
    }
};