<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        DB::unprepared("
            CREATE TABLE clientes (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                nombreCompleto VARCHAR2(255) NOT NULL,
                telefono VARCHAR2(50) NOT NULL,
                direccion VARCHAR2(255) NOT NULL,
                idUsuario NUMBER NOT NULL,
                CONSTRAINT fk_clientes_usuarios FOREIGN KEY (idUsuario) REFERENCES usuarios(id)
            )
        ");
        
        // Procedimiento para consultar todos los clientes
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarClientes IS
            BEGIN
                -- Puedes abrir un cursor aquí si lo necesitas
                NULL;
            END;
        ");
        
        // Procedimiento para consultar un cliente por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarClientePorId(p_id IN NUMBER) IS
            BEGIN
                -- Puedes abrir un cursor aquí si lo necesitas
                NULL;
            END;
        ");
        
        // Procedimiento para actualizar un cliente
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarCliente(
                p_id IN NUMBER,
                p_nombreCompleto IN VARCHAR2,
                p_telefono IN VARCHAR2,
                p_direccion IN VARCHAR2,
                p_idUsuario IN NUMBER
            ) IS
            BEGIN
                UPDATE clientes
                SET nombreCompleto = p_nombreCompleto,
                    telefono = p_telefono,
                    direccion = p_direccion,
                    idUsuario = p_idUsuario
                WHERE id = p_id;
                COMMIT;
            END;
        ");
        
        // Procedimiento para eliminar un cliente por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarClientePorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM clientes WHERE id = p_id;
                COMMIT;
            END;
        ");
        
        // Nuevo procedimiento para insertar un cliente y retornar su id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE InsertarCliente(
                p_nombreCompleto IN VARCHAR2,
                p_telefono IN VARCHAR2,
                p_direccion IN VARCHAR2,
                p_idUsuario IN NUMBER,
                p_id OUT NUMBER
            ) IS
            BEGIN
                INSERT INTO clientes (nombreCompleto, telefono, direccion, idUsuario)
                VALUES (p_nombreCompleto, p_telefono, p_direccion, p_idUsuario)
                RETURNING id INTO p_id;
                COMMIT;
            END;
        ");
    }
    
    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarClientes");
        DB::unprepared("DROP PROCEDURE ConsultarClientePorId");
        DB::unprepared("DROP PROCEDURE ActualizarCliente");
        DB::unprepared("DROP PROCEDURE EliminarClientePorId");
        DB::unprepared("DROP PROCEDURE InsertarCliente");
        
        DB::unprepared("DROP TABLE clientes");
    }
};