<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        // Crea la tabla productos_usados_cita (solo referencia)
        DB::unprepared("
            CREATE TABLE productos_usados_cita (
                id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                citaId         NUMBER NOT NULL,
                inventarioId   NUMBER NOT NULL,
                CONSTRAINT fk_puc_cita       FOREIGN KEY (citaId)       REFERENCES citas(id),
                CONSTRAINT fk_puc_inventario FOREIGN KEY (inventarioId) REFERENCES inventario(id)
            )
        ");

        // Función para descontar unidades del inventario y devolver el nuevo stock
        DB::unprepared("
            CREATE OR REPLACE FUNCTION DescontarUnidadesProducto(
                p_inventarioId IN NUMBER,
                p_cantidad     IN NUMBER
            ) RETURN NUMBER IS
                v_nuevaCantidadProducto NUMBER;
            BEGIN
                UPDATE inventario
                   SET cantidadUnidades = cantidadUnidades - p_cantidad
                 WHERE id = p_inventarioId
                 RETURNING cantidadUnidades INTO v_nuevaCantidadProducto;
                RETURN v_nuevaCantidadProducto;
            END DescontarUnidadesProducto;
        ");

        // SP: consultar productos usados en una cita
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarProductosUsadosCitaPorId(
                p_citaId IN NUMBER,
                cur      OUT SYS_REFCURSOR
            ) IS
            BEGIN
                OPEN cur FOR
                SELECT id, citaId, inventarioId
                  FROM productos_usados_cita
                 WHERE citaId = p_citaId;
            END;
        ");

        // SP: insertar producto usado en cita y descontar stock con la función
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE InsertarProductoUsadoCita(
                p_citaId       IN NUMBER,
                p_inventarioId IN NUMBER,
                p_cantidad     IN NUMBER,
                p_id           OUT NUMBER
            ) IS
                v_cantidadProducto NUMBER;
            BEGIN
                -- registra enlace cita-producto
                INSERT INTO productos_usados_cita (citaId, inventarioId)
                VALUES (p_citaId, p_inventarioId)
                RETURNING id INTO p_id;

                -- descuenta unidades usando la función y opcionalmente usa v_cantidadProducto
                v_cantidadProducto := DescontarUnidadesProducto(p_inventarioId, p_cantidad);

                COMMIT;
            END;
        ");

        // SP: elimina registros de productos usados en una cita
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarProductosUsadosCitaPorId(
                p_citaId IN NUMBER
            ) IS
            BEGIN
                DELETE FROM productos_usados_cita
                 WHERE citaId = p_citaId;
                COMMIT;
            END;
        ");
    }

    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarProductosUsadosCitaPorId");
        DB::unprepared("DROP PROCEDURE InsertarProductoUsadoCita");
        DB::unprepared("DROP PROCEDURE EliminarProductosUsadosCitaPorId");
        DB::unprepared("DROP FUNCTION DescontarUnidadesProducto");
        DB::unprepared("DROP TABLE productos_usados_cita");
    }
};