<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        DB::unprepared("
            CREATE TABLE servicios (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                nombre VARCHAR2(255) NOT NULL,
                descripcion CLOB NOT NULL,
                precio NUMBER(10,2) NOT NULL,
                duracion NUMBER NOT NULL
            )
        ");

        // Convert ConsultarServicios procedure to use an OUT parameter for the cursor
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarServicios(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM servicios;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarServicioPorId(p_id IN NUMBER, cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM servicios WHERE id = p_id;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarServicio(
                p_id IN NUMBER,
                p_nombre IN VARCHAR2,
                p_descripcion IN CLOB,
                p_precio IN NUMBER,
                p_duracion IN NUMBER
            ) IS
            BEGIN
                UPDATE servicios
                SET nombre = p_nombre,
                    descripcion = p_descripcion,
                    precio = p_precio,
                    duracion = p_duracion
                WHERE id = p_id;
                COMMIT;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarServicioPorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM servicios WHERE id = p_id;
                COMMIT;
            END;
        ");
    }
    
    public function down(): void
    {
        // Drop stored procedures first
        DB::unprepared("DROP PROCEDURE ConsultarServicios");
        DB::unprepared("DROP PROCEDURE ConsultarServicioPorId");
        DB::unprepared("DROP PROCEDURE ActualizarServicio");
        DB::unprepared("DROP PROCEDURE EliminarServicioPorId");
        
        DB::unprepared("DROP TABLE servicios");
    }
};