<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        DB::unprepared("
            CREATE TABLE mascotas (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                nombre_completo VARCHAR2(255) NOT NULL,
                edad NUMBER NOT NULL,
                peso NUMBER(5,2) NOT NULL,
                raza VARCHAR2(255) NOT NULL,
                especie VARCHAR2(255) NOT NULL,
                idCliente NUMBER NOT NULL,
                CONSTRAINT fk_mascotas_clientes FOREIGN KEY (idCliente) REFERENCES clientes(id)
            )
        ");

        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarMascotas(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM mascotas;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarMascotaPorId(p_id IN NUMBER, cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM mascotas WHERE id = p_id;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarMascotasPorUsuarioId(p_idUsuario IN NUMBER, cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR 
                    SELECT m.* 
                    FROM mascotas m
                    JOIN clientes c ON m.idCliente = c.id
                    JOIN usuarios u ON c.idUsuario = u.id
                    WHERE u.id = p_idUsuario;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarMascota(
                p_id IN NUMBER,
                p_nombre_completo IN VARCHAR2,
                p_edad IN NUMBER,
                p_peso IN NUMBER,
                p_raza IN VARCHAR2,
                p_especie IN VARCHAR2,
                p_idCliente IN NUMBER
            ) IS
            BEGIN
                UPDATE mascotas
                SET nombre_completo = p_nombre_completo,
                    edad = p_edad,
                    peso = p_peso,
                    raza = p_raza,
                    especie = p_especie,
                    idCliente = p_idCliente
                WHERE id = p_id;
                COMMIT;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarMascotaPorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM mascotas WHERE id = p_id;
                COMMIT;
            END;
        ");
        
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE InsertarMascota(
                p_nombre_completo IN VARCHAR2,
                p_edad IN NUMBER,
                p_peso IN NUMBER,
                p_raza IN VARCHAR2,
                p_especie IN VARCHAR2,
                p_idCliente IN NUMBER,
                p_id OUT NUMBER
            ) IS
            BEGIN
                INSERT INTO mascotas (nombre_completo, edad, peso, raza, especie, idCliente)
                VALUES (p_nombre_completo, p_edad, p_peso, p_raza, p_especie, p_idCliente)
                RETURNING id INTO p_id;
                COMMIT;
            END;
        ");
    }
    
    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarMascotas");
        DB::unprepared("DROP PROCEDURE ConsultarMascotaPorId");
        DB::unprepared("DROP PROCEDURE ConsultarMascotasPorUsuarioId");
        DB::unprepared("DROP PROCEDURE ActualizarMascota");
        DB::unprepared("DROP PROCEDURE EliminarMascotaPorId");
        DB::unprepared("DROP PROCEDURE InsertarMascota");
        DB::unprepared("DROP TABLE mascotas CASCADE CONSTRAINTS PURGE");
    }
};