<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        // Crea la tabla usuarios
        DB::unprepared("
            CREATE TABLE usuarios (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                email VARCHAR2(255) NOT NULL UNIQUE,
                password VARCHAR2(255) NOT NULL,
                role VARCHAR2(50) NOT NULL
            )
        ");

        // Procedimiento para consultar todos los usuarios
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarUsuarios(cur OUT SYS_REFCURSOR) IS
            BEGIN
                OPEN cur FOR SELECT * FROM usuarios;
            END;
        ");

        // Procedimiento para consultar un usuario por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarUsuarioPorId(
                p_id IN NUMBER, 
                cur OUT SYS_REFCURSOR
            ) IS
            BEGIN
                OPEN cur FOR SELECT * FROM usuarios WHERE id = p_id;
            END;
        ");

        // Procedimiento para consultar un usuario por correo
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarUsuarioPorCorreo(
                p_email IN VARCHAR2,
                cur OUT SYS_REFCURSOR
            ) IS
            BEGIN
                OPEN cur FOR SELECT * FROM usuarios WHERE email = p_email;
            END;
        ");

        // Procedimiento para actualizar un usuario
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarUsuario(
                p_id IN NUMBER,
                p_email IN VARCHAR2,
                p_password IN VARCHAR2,
                p_role IN VARCHAR2
            ) IS
            BEGIN
                UPDATE usuarios
                SET email = p_email,
                    password = p_password,
                    role = p_role
                WHERE id = p_id;
                COMMIT;
            END;
        ");

        // Procedimiento para eliminar un usuario por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarUsuarioPorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM usuarios WHERE id = p_id;
                COMMIT;
            END;
        ");

        // Nuevo procedimiento para insertar un usuario y retornar su id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE InsertarUsuario(
                p_email IN VARCHAR2,
                p_password IN VARCHAR2,
                p_role IN VARCHAR2,
                p_id OUT NUMBER
            ) IS
            BEGIN
                INSERT INTO usuarios (email, password, role)
                VALUES (p_email, p_password, p_role)
                RETURNING id INTO p_id;
                COMMIT;
            END;
        ");
    }

    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarUsuarios");
        DB::unprepared("DROP PROCEDURE ConsultarUsuarioPorId");
        DB::unprepared("DROP PROCEDURE ConsultarUsuarioPorCorreo");
        DB::unprepared("DROP PROCEDURE ActualizarUsuario");
        DB::unprepared("DROP PROCEDURE EliminarUsuarioPorId");
        DB::unprepared("DROP PROCEDURE InsertarUsuario");

        DB::unprepared("DROP TABLE usuarios");
    }
};