<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        // Tabla horarios de sucursal
        DB::unprepared("
            CREATE TABLE sucursal_horarios (
                id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                idSucursal     NUMBER NOT NULL,
                dia_semana     NUMBER(1)      NOT NULL,  -- 1=Lun … 7=Dom
                hora_apertura  VARCHAR2(5)    NOT NULL,  -- '08:00', '17:30'
                hora_cierre    VARCHAR2(5)    NOT NULL,
                esta_abierto   NUMBER(1)      DEFAULT 1 NOT NULL,
                CONSTRAINT fk_horarios_sucursales FOREIGN KEY (idSucursal) REFERENCES sucursales(id)
            )
        ");

        // SP: Consultar horarios por sucursal
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ConsultarHorariosPorSucursal(
                p_idSucursal IN NUMBER,
                cur          OUT SYS_REFCURSOR
            ) IS
            BEGIN
                OPEN cur FOR
                  SELECT id, dia_semana, hora_apertura, hora_cierre, esta_abierto
                    FROM sucursal_horarios
                   WHERE idSucursal = p_idSucursal
                ORDER BY dia_semana;
            END;
        ");

        // SP: Insertar horario
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE InsertarHorario(
                p_idSucursal     IN NUMBER,
                p_dia_semana     IN NUMBER,
                p_hora_apertura  IN VARCHAR2,
                p_hora_cierre    IN VARCHAR2,
                p_esta_abierto   IN NUMBER,
                p_id             OUT NUMBER
            ) IS
            BEGIN
                INSERT INTO sucursal_horarios(
                  idSucursal, dia_semana, hora_apertura, hora_cierre, esta_abierto
                ) VALUES (
                  p_idSucursal, p_dia_semana, p_hora_apertura, p_hora_cierre, p_esta_abierto
                )
                RETURNING id INTO p_id;
                COMMIT;
            END;
        ");

        // SP: Actualizar horario
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE ActualizarHorario(
                p_id             IN NUMBER,
                p_hora_apertura  IN VARCHAR2,
                p_hora_cierre    IN VARCHAR2,
                p_esta_abierto   IN NUMBER
            ) IS
            BEGIN
                UPDATE sucursal_horarios
                   SET hora_apertura = p_hora_apertura,
                       hora_cierre   = p_hora_cierre,
                       esta_abierto  = p_esta_abierto
                 WHERE id = p_id;
                COMMIT;
            END;
        ");

        // SP: Eliminar horario por id
        DB::unprepared("
            CREATE OR REPLACE PROCEDURE EliminarHorarioPorId(p_id IN NUMBER) IS
            BEGIN
                DELETE FROM sucursal_horarios WHERE id = p_id;
                COMMIT;
            END;
        ");
    }

    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE ConsultarHorariosPorSucursal");
        DB::unprepared("DROP PROCEDURE InsertarHorario");
        DB::unprepared("DROP PROCEDURE ActualizarHorario");
        DB::unprepared("DROP PROCEDURE EliminarHorarioPorId");
        DB::unprepared("DROP TABLE sucursal_horarios");
    }
};